# The hostname that gets set inside the VM.
# When using browsersync for front-end development we need to proxy the vm and the .local hostname is already in use by the native Bonjour app on OSX.
# Using local for the hostname makes browsersync unusable in this configuration, so we have updated the local hostname to vm instead.
hostname: "local.zivtech.com"
# The private IP to provision for this host.
private_ipv4: "172.16.0.2"
private_ipv6: "2400:cb00:2049:1::a29f:1a63"
# The base box to use to build the puppet work on top of.
# Change the version number in the line below (or override in config.yaml)
# to switch Ubuntu versions.
box: "zivtech/ubuntu-16.04-server-puppet-4"
box_version: "1.0"
# The amount of memory (in megabytes) to provision.
memory: "2048"
cpus: 2
# Set this to false in order to not mount the www folder in this
# directory inside `/var/www` on the VM.
sync_folder: true
# If we detect we are running on windows, whether we should enable
# the sync folder. Note, this uses VirtualBox folder sharing which
# is not compatible with symlinks and some other important features.
sync_file_enabled_on_windows: false
