#! /bin/bash

while getopts hp: opt; do
  case $opt in
    h)
      echo "This program is designed to fix file permissions on an ubuntu/debian system in accordance with https://drupal.org/node/244924."
      echo "Execute it from the directory that contains the drupal code directory."
      echo "A setup with code pulbic_file and private_files as peers is assumed."
      echo "Use -p [pathname] to specify a particular path. Otherwise the assumption is that it is the current working directory."
      echo "You may need to run with sudo or as root in order to correctly set the file permissions."
      exit 0;
      ;;
    p)
      echo "Working in directory $OPTARG"
      cd $OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done
CURRENT=`pwd`
CODE_DIR=`readlink $CURRENT/webroot`
PUB_FILES_DIR='public_files'
PRIVATE_FILES_DIR='private_files'
APACHE_USER='www-data'
GIT_DIR='.git'

# Recursively change directory and file ownership for all files to the :webadmin group
echo "Changing directory and file ownership to webadmin user and group."
chown -R :webadmin $CURRENT

echo "Changing public and private file ownership to the www-data group."
chown -R :www-data $CURRENT/$PUB_FILES_DIR $CURRENT/$PRIVATE_FILES_DIR

if [ -e "${CURRENT}/public_files/.git" ] ; then
  echo "Ensure group ownership of the webadmin group for git based public_files backups."
  chown -R :webadmin $CURRENT/$PUB_FILES_DIR/.git
fi

if [ -e "${CURRENT}/$PRIVATE_FILES_DIR/.git" ] ; then
  echo "Ensure group ownership of the webadmin group for git based private_files backups."
  chown -R :webadmin $CURRENT/$PRIVATE_FILES_DIR/.git
fi

#@TODO Skip public/private files, they get changed in the next step.
echo "Changing permissions on all files to be sticky user writeable, group writeable, and world readable"
chmod -R 2775 $CURRENT 

echo "Changing permissions on all ./webroot files to be sticky user writeable, group writeable, and world readable"
chmod -R 2770 $CURRENT/$PUB_FILES_DIR
chmod -R 2770 $CURRENT/$PRIVATE_FILES_DIR

echo "Making sites folder php files group owned by www-data and exclusively group readable"
chmod 0550 $CODE_DIR/sites/*/*.php
chown :www-data $CODE_DIR/sites/*/*.php
